use actnow2024;

-- Inserindo dados na tabela de turnos do dia
insert into turnodia(turnomeclatura)
values ('Manhã'),
		('Tarde'),
        ('Noite');

-- Inserindo dados na tabela de dias da semana
insert into diasemana(dsnomeclatura)
values ('Segunda-Feira'),
		('Terça-Feira'),
        ('Quarta-Feira'),
        ('Quinta-Feira'),
        ('Sexta-Feira'),
        ('Sábado'),
        ('Domingo');
        
-- Inserindo dados na tabela de habilidades
insert into habilidade(habnome)
values ('Artesanato'),
		('Marcenaria'),
		('Costura'),
		('Cerâmica'),
		('Pintura'),
		('Jardinagem'),
		('Construção Civil'),
		('Encanador'),
		('Eletricista'),
		('Esculpir'),
		('Joalheria'),
		('Tecelagem'),
		('Serralheria'),
		('Bordado'),
		('Vidraria'),
		('Encadernação'),
		('Carpintaria');

-- Inserindo dadois na tabela de estados do brasil
insert into estado(estsigla, estnome)
values ('AC', 'Acre'),
		('AL', 'Alagoas'),
		('AP', 'Amapá'),
		('AM', 'Amazonas'),
		('BA', 'Bahia'),
		('CE', 'Ceará'),
		('DF', 'Distrito Federal'),
		('ES', 'Espírito Santo'),
		('GO', 'Goiás'),
		('MA', 'Maranhão'),
		('MT', 'Mato Grosso'),
		('MS', 'Mato Grosso do Sul'),
		('MG', 'Minas Gerais'),
		('PA', 'Pará'),
		('PB', 'Paraíba'),
		('PR', 'Paraná'),
		('PE', 'Pernambuco'),
		('PI', 'Piauí'),
		('RJ', 'Rio de Janeiro'),
		('RN', 'Rio Grande do Norte'),
		('RS', 'Rio Grande do Sul'),
		('RO', 'Rondônia'),
		('RR', 'Roraima'),
		('SC', 'Santa Catarina'),
		('SP', 'São Paulo'),
		('SE', 'Sergipe'),
		('TO', 'Tocantins');

-- Inserindo dados do Acre na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Rio Branco', 1),
		('Cruzeiro do Sul', 1),
		('Sena Madureira', 1),
		('Tarauacá', 1),
		('Feijó', 1),
		('Plácido de Castro', 1),
		('Xapuri', 1),
		('Brasiléia', 1),
		('Mâncio Lima', 1),
		('Porto Acre', 1),
		('Epitaciolândia', 1),
		('Assis Brasil', 1),
		('Senador Guiomard', 1),
		('Jordão', 1),
		('Manoel Urbano', 1),
		('Santa Rosa do Purus', 1),
		('Porto Walter', 1),
		('Bujari', 1),
		('Capixaba', 1),
		('Marechal Thaumaturgo', 1);
        
-- Inserindo dados do Alagoas na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Maceió', 2),
		('Arapiraca', 2),
		('Rio Largo', 2),
		('Palmeira dos Índios', 2),
		('Marechal Deodoro', 2),
		('Penedo', 2),
		('São Miguel dos Campos', 2),
		('Campo Alegre', 2),
		('União dos Palmares', 2),
		('Delmiro Gouveia', 2),
		('Coruripe', 2),
		('Atalaia', 2),
		('Santana do Ipanema', 2),
		('Teotônio Vilela', 2),
		('Girau do Ponciano', 2),
		('Satuba', 2),
		('Murici', 2),
		('Pilar', 2),
		('São Luís do Quitunde', 2),
		('São José da Tapera', 2);
        
-- Inserindo dados do Amapá na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Macapá', 3),
		('Santana', 3),
		('Laranjal do Jari', 3),
		('Oiapoque', 3),
		('Porto Grande', 3),
		('Mazagão', 3),
		('Tartarugalzinho', 3),
		('Pedra Branca do Amapari', 3),
		('Serra do Navio', 3),
		('Cutias', 3),
		('Ferreira Gomes', 3),
		('Calçoene', 3),
		('Itaubal', 3),
		('Pracuúba', 3),
		('Amapá', 3),
		('Vitória do Jari', 3),
		('Serra do Navio', 3),
		('Tartarugalzinho', 3),
		('Porto Grande', 3),
		('Pedra Branca do Amapari', 3);
        
-- Inserindo dados do Amazonas na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Manaus', 4),
		('Parintins', 4),
		('Itacoatiara', 4),
		('Manacapuru', 4),
		('Coari', 4),
		('Tabatinga', 4),
		('Maués', 4),
		('Tefé', 4),
		('Manicoré', 4),
		('Humaitá', 4),
		('Borba', 4),
		('São Gabriel da Cachoeira', 4),
		('Eirunepé', 4),
		('Autazes', 4),
		('Nova Olinda do Norte', 4),
		('Barreirinha', 4),
		('Boca do Acre', 4),
		('São Paulo de Olivença', 4),
		('Benjamin Constant', 4),
		('Manacapuru', 4);
        
-- Inserindo dados da Bahia na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Salvador', 5),
		('Feira de Santana', 5),
		('Vitória da Conquista', 5),
		('Camaçari', 5),
		('Itabuna', 5),
		('Juazeiro', 5),
		('Ilhéus', 5),
		('Lauro de Freitas', 5),
		('Jequié', 5),
		('Teixeira de Freitas', 5),
		('Alagoinhas', 5),
		('Barreiras', 5),
		('Porto Seguro', 5),
		('Simões Filho', 5),
		('Paulo Afonso', 5),
		('Santo Antônio de Jesus', 5),
		('Valença', 5),
		('Eunápolis', 5),
		('Serrinha', 5),
		('Luís Eduardo Magalhães', 5);

-- Inserindo dados do Ceará tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Fortaleza', 6),
		('Caucaia', 6),
		('Juazeiro do Norte', 6),
		('Maracanaú', 6),
		('Sobral', 6),
		('Itapipoca', 6),
		('Crato', 6),
		('Maracanaú', 6),
		('Quixadá', 6),
		('Iguatu', 6),
		('Pacatuba', 6),
		('Quixeramobim', 6),
		('Russas', 6),
		('Canindé', 6),
		('Crateús', 6),
		('Aracati', 6),
		('Cascavel', 6),
		('Icó', 6),
		('Tianguá', 6),
		('Horizonte', 6);

-- Inserindo dados do Distrito Federal na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Brasília', 7),
		('Ceilândia', 7),
		('Taguatinga', 7),
		('Planaltina', 7),
		('Gama', 7),
		('Santa Maria', 7),
		('Sobradinho', 7),
		('Paranoá', 7),
		('Núcleo Bandeirante', 7),
		('Águas Claras', 7),
		('Candangolândia', 7),
		('Riacho Fundo', 7),
		('Samambaia', 7),
		('Brazlândia', 7),
		('São Sebastião', 7),
		('Recanto das Emas', 7),
		('Lago Sul', 7),
		('Varjão', 7),
		('Lago Norte', 7),
		('Itapoã', 7);

-- Inserindo dados do Espírito Santo na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Vitória', 8),
		('Vila Velha', 8),
		('Serra', 8),
		('Cariacica', 8),
		('Cachoeiro de Itapemirim', 8),
		('Linhares', 8),
		('São Mateus', 8),
		('Colatina', 8),
		('Guarapari', 8),
		('Aracruz', 8),
		('Nova Venécia', 8),
		('Barra de São Francisco', 8),
		('Castelo', 8),
		('Itapemirim', 8),
		('Marataízes', 8),
		('Rio Bananal', 8),
		('Santa Teresa', 8),
		('Jaguaré', 8),
		('Viana', 8),
		('Anchieta', 8);

-- Inserindo dados de Goiás na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Goiânia', 9),
		('Aparecida de Goiânia', 9),
		('Anápolis', 9),
		('Rio Verde', 9),
		('Luziânia', 9),
		('Águas Lindas de Goiás', 9),
		('Valparaíso de Goiás', 9),
		('Trindade', 9),
		('Formosa', 9),
		('Novo Gama', 9),
		('Itumbiara', 9),
		('Senador Canedo', 9),
		('Catalão', 9),
		('Jataí', 9),
		('Caldas Novas', 9),
		('Planaltina', 9),
		('Porangatu', 9),
		('Cristalina', 9),
		('Jaraguá', 9),
		('Niquelândia', 9);

-- Inserindo dados do Maranhão na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('São Luís', 10),
		('Imperatriz', 10),
		('São José de Ribamar', 10),
		('Timon', 10),
		('Caxias', 10),
		('Codó', 10),
		('Paço do Lumiar', 10),
		('Açailândia', 10),
		('Bacabal', 10),
		('Balsas', 10),
		('Barra do Corda', 10),
		('Santa Inês', 10),
		('Pinheiro', 10),
		('Chapadinha', 10),
		('Santa Luzia', 10),
		('Coroatá', 10),
		('Tutóia', 10),
		('Pedreiras', 10),
		('Grajaú', 10),
		('Coelho Neto', 10);

-- Inserindo dados do Mato Grosso na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Cuiabá', 11),
		('Várzea Grande', 11),
		('Rondonópolis', 11),
		('Sinop', 11),
		('Tangará da Serra', 11),
		('Cáceres', 11),
		('Sorriso', 11),
		('Lucas do Rio Verde', 11),
		('Primavera do Leste', 11),
		('Barra do Garças', 11),
		('Alta Floresta', 11),
		('Ponta Porã', 11),
		('Campo Verde', 11),
		('Juína', 11),
		('Rondonópolis', 11),
		('Colíder', 11),
		('Juara', 11),
		('Pontes e Lacerda', 11),
		('Barra do Bugres', 11),
		('Guarantã do Norte', 11);

-- Inserindo dados do Mato Grosso do Sul na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Campo Grande', 12),
		('Dourados', 12),
		('Três Lagoas', 12),
		('Corumbá', 12),
		('Ponta Porã', 12),
		('Naviraí', 12),
		('Nova Andradina', 12),
		('Aquidauana', 12),
		('Paranaíba', 12),
		('Maracaju', 12),
		('Amambai', 12),
		('Rio Brilhante', 12),
		('Coxim', 12),
		('Caarapó', 12),
		('Miranda', 12),
		('Sidrolândia', 12),
		('Jardim', 12),
		('Bela Vista', 12),
		('Cassilândia', 12),
		('Ivinhema', 12);

-- Inserindo dados de Minas Gerais na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Belo Horizonte', 13),
		('Uberlândia', 13),
		('Contagem', 13),
		('Juiz de Fora', 13),
		('Betim', 13),
		('Montes Claros', 13),
		('Ribeirão das Neves', 13),
		('Uberaba', 13),
		('Governador Valadares', 13),
		('Ipatinga', 13),
		('Sete Lagoas', 13),
		('Divinópolis', 13),
		('Santa Luzia', 13),
		('Ibirité', 13),
		('Poços de Caldas', 13),
		('Patos de Minas', 13),
		('Teófilo Otoni', 13),
		('Sabará', 13),
		('Pouso Alegre', 13),
		('Varginha', 13);

-- Inserindo dados do Pará na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Belém', 14),
		('Ananindeua', 14),
		('Santarém', 14),
		('Marabá', 14),
		('Parauapebas', 14),
		('Castanhal', 14),
		('Abaetetuba', 14),
		('Itaituba', 14),
		('Cametá', 14),
		('Bragança', 14),
		('Marabá', 14),
		('Tucuruí', 14),
		('Altamira', 14),
		('Paragominas', 14),
		('Tailândia', 14),
		('Breves', 14),
		('Santarém', 14),
		('Redenção', 14),
		('Moju', 14),
		('Oriximiná', 14);

-- Inserindo dados de Paraíba na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('João Pessoa', 15),
		('Campina Grande', 15),
		('Santa Rita', 15),
		('Patos', 15),
		('Bayeux', 15),
		('Cabedelo', 15),
		('Sousa', 15),
		('Cajazeiras', 15),
		('Guarabira', 15),
		('Mamanguape', 15),
		('Queimadas', 15),
		('Rio Tinto', 15),
		('Lagoa Seca', 15),
		('Itaporanga', 15),
		('Conde', 15),
		('Catolé do Rocha', 15),
		('Esperança', 15),
		('Solânea', 15),
		('Pedras de Fogo', 15),
		('Itabaiana', 15);
        
-- Inserindo dados do Paraná na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Curitiba', 16),
		('Londrina', 16),
		('Maringá', 16),
		('Ponta Grossa', 16),
		('Cascavel', 16),
		('São José dos Pinhais', 16),
		('Foz do Iguaçu', 16),
		('Colombo', 16),
		('Guarapuava', 16),
		('Paranaguá', 16),
		('Apucarana', 16),
		('Toledo', 16),
		('Pinhais', 16),
		('Araucária', 16),
		('Campo Largo', 16),
		('Arapongas', 16),
		('Almirante Tamandaré', 16),
		('Umuarama', 16),
		('Piraquara', 16),
		('Cambé', 16);

-- Inserindo dados de Pernambuco na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Jaboatão dos Guararapes', 17),
		('Olinda', 17),
		('Caruaru', 17),
		('Petrolina', 17),
		('Paulista', 17),
		('Cabo de Santo Agostinho', 17),
		('Camaragibe', 17),
		('Garanhuns', 17),
		('Vitória de Santo Antão', 17),
		('Igarassu', 17),
		('São Lourenço da Mata', 17),
		('Santa Cruz do Capibaribe', 17),
		('Abreu e Lima', 17),
		('Serra Talhada', 17),
		('Araripina', 17),
		('Gravatá', 17),
		('Carpina', 17),
		('Goiana', 17),
		('Belo Jardim', 17);

-- Inserindo dados do Piauí na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Teresina', 18),
		('Parnaíba', 18),
		('Picos', 18),
		('Piripiri', 18),
		('Floriano', 18),
		('Campo Maior', 18),
		('Altos', 18),
		('José de Freitas', 18),
		('Barras', 18),
		('União', 18),
		('Esperantina', 18),
		('Oeiras', 18),
		('Pedro II', 18),
		('Luís Correia', 18),
		('Miguel Alves', 18),
		('Batalha', 18),
		('São Raimundo Nonato', 18),
		('Monsenhor Gil', 18),
		('Cocal', 18),
		('Água Branca', 18);

-- Inserindo dados do Rio de Janeiro na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Rio de Janeiro', 19),
		('São Gonçalo', 19),
		('Duque de Caxias', 19),
		('Nova Iguaçu', 19),
		('Niterói', 19),
		('Campos dos Goytacazes', 19),
		('Belford Roxo', 19),
		('São João de Meriti', 19),
		('Petrópolis', 19),
		('Volta Redonda', 19),
		('Magé', 19),
		('Itaboraí', 19),
		('Mesquita', 19),
		('Nova Friburgo', 19),
		('Barra Mansa', 19),
		('Macae', 19),
		('Cabo Frio', 19),
		('Nilópolis', 19),
		('Angra dos Reis', 19),
		('Teresópolis', 19);
        
-- Inserindo dados do Rio Grande do Norte na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Natal', 20),
		('Mossoró', 20),
		('Parnamirim', 20),
		('São Gonçalo do Amarante', 20),
		('Macaíba', 20),
		('Ceará-Mirim', 20),
		('Caicó', 20),
		('Açu', 20),
		('Currais Novos', 20),
		('São José de Mipibu', 20),
		('Apodi', 20),
		('Nova Cruz', 20),
		('João Câmara', 20),
		('Extremoz', 20),
		('Pau dos Ferros', 20),
		('Areia Branca', 20),
		('Santa Cruz', 20),
		('Canguaretama', 20),
		('Jucurutu', 20),
		('Baraúna', 20);


-- Inserindo dados do Rio Grande do Sul na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Porto Alegre', 21),
		('Caxias do Sul', 21),
		('Pelotas', 21),
		('Canoas', 21),
		('Santa Maria', 21),
		('Gravataí', 21),
		('Viamão', 21),
		('Novo Hamburgo', 21),
		('São Leopoldo', 21),
		('Rio Grande', 21),
		('Alvorada', 21),
		('Passo Fundo', 21),
		('Sapucaia do Sul', 21),
		('Uruguaiana', 21),
		('Cachoeirinha', 21),
		('Bagé', 21),
		('Santa Cruz do Sul', 21),
		('Bento Gonçalves', 21),
		('Erechim', 21),
		('Guaíba', 21);

-- Inserindo dados de Rondônia na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Porto Velho', 22),
		('Ji-Paraná', 22),
		('Ariquemes', 22),
		('Vilhena', 22),
		('Cacoal', 22),
		('Rolim de Moura', 22),
		('Guajará-Mirim', 22),
		('Jaru', 22),
		('Ouro Preto do Oeste', 22),
		('Pimenta Bueno', 22),
		('Buritis', 22),
		('Espigão d Oeste', 22),
		('Candeias do Jamari', 22),
		('Nova Mamoré', 22),
		('Machadinho d Oeste', 22),
		('Cujubim', 22),
		('Alvorada d Oeste', 22),
		('Alta Floresta d Oeste', 22),
		('Presidente Médici', 22),
		('São Miguel do Guaporé', 22);

-- Inserindo dados de Roraima na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Boa Vista', 23),
		('Caracaraí', 23),
		('Rorainópolis', 23),
		('Pacaraima', 23),
		('São João da Baliza', 23),
		('São Luiz', 23),
		('Mucajaí', 23),
		('Alto Alegre', 23),
		('Caroebe', 23),
		('Bonfim', 23),
		('Uiramutã', 23),
		('Normandia', 23),
		('Iracema', 23),
		('Amajari', 23),
		('Pacaraima', 23),
		('São Luiz', 23),
		('Caroebe', 23),
		('Alto Alegre', 23),
		('Mucajaí', 23),
		('São João da Baliza', 23);
        
-- Inserindo dados de Santa Catarina na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Florianópolis', 24),
		('Joinville', 24),
		('Blumenau', 24),
		('São José', 24),
		('Chapecó', 24),
		('Criciúma', 24),
		('Itajaí', 24),
		('Jaraguá do Sul', 24),
		('Palhoça', 24),
		('Lages', 24),
		('Balneário Camboriú', 24),
		('Brusque', 24),
		('Tubarão', 24),
		('São Bento do Sul', 24),
		('Caçador', 24),
		('Concórdia', 24),
		('Rio do Sul', 24),
		('Araranguá', 24),
		('Indaial', 24),
		('Imbituba', 24);

-- Inserindo dados de São Paulo na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('São Paulo', 25),
		('Guarulhos', 25),
		('Campinas', 25),
		('São Bernardo do Campo', 25),
		('Osasco', 25),
		('Santo André', 25),
		('São José dos Campos', 25),
		('Ribeirão Preto', 25),
		('Sorocaba', 25),
		('Mauá', 25),
		('São José do Rio Preto', 25),
		('Mogi das Cruzes', 25),
		('Diadema', 25),
		('Jundiaí', 25),
		('Piracicaba', 25),
		('Carapicuíba', 25),
		('Bauru', 25),
		('Itaquaquecetuba', 25),
		('São Vicente', 25),
		('Santos', 25);

-- Inserindo dados de Sergipe na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Aracaju', 26),
		('Nossa Senhora do Socorro', 26),
		('Lagarto', 26),
		('Itabaiana', 26),
		('São Cristóvão', 26),
		('Estância', 26),
		('Nossa Senhora da Glória', 26),
		('Tobias Barreto', 26),
		('Itabaianinha', 26),
		('Simão Dias', 26),
		('Umbaúba', 26),
		('Capela', 26),
		('Propriá', 26),
		('Barra dos Coqueiros', 26),
		('Poço Verde', 26),
		('Boquim', 26),
		('Canindé de São Francisco', 26),
		('Laranjeiras', 26),
		('Carmópolis', 26),
		('Nossa Senhora das Dores', 26);

-- Inserindo dados de Tocantins na tabela de cidade 
insert into cidade(cidnome, cidestcod)
values ('Palmas', 27),
		('Araguaína', 27),
		('Gurupi', 27),
		('Porto Nacional', 27),
		('Paraíso do Tocantins', 27),
		('Araguatins', 27),
		('Colinas do Tocantins', 27),
		('Guaraí', 27),
		('Tocantinópolis', 27),
		('Dianópolis', 27),
		('Formoso do Araguaia', 27),
		('Miracema do Tocantins', 27), 
		('Pedro Afonso', 27),
		('Augustinópolis', 27),
		('Araguaçu', 27),
		('Nova Olinda', 27),
		('Wanderlândia', 27),
		('Xambioá', 27),
		('Alvorada', 27),
		('Ananás', 27);
        
        
        